//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_emails
    {
        public int id { get; set; }
        public string sent_from { get; set; }
        public string contents { get; set; }
        public Nullable<System.DateTime> sent_datetime { get; set; }
        public string status { get; set; }
    }
}
