//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public string title { get; set; }
        public string for_name { get; set; }
        public string type { get; set; }
        public string status { get; set; }
        public Nullable<int> sales_order_id { get; set; }
        public Nullable<int> total_amount { get; set; }
        public Nullable<int> manager_id { get; set; }
        public string file { get; set; }
    
        public virtual User User { get; set; }
    }
}
